/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class CadastrarPlanoAlimentar extends javax.swing.JFrame {

    /**
     * Creates new form PerfilPacienteNutri
     * @param ID1
     * @param CPF1
     */
    String id, opcao1, opcao2, opcao3, Desjejum1, Desjejum2, Desjejum3, Desjejum4, Desjejum5, Desjejum6, Desjejum7, Almoco1, Almoco2, Almoco3, Almoco4, Almoco5, Almoco6, Almoco7, Lanche1, Lanche2, Lanche3, Lanche4, Lanche5, Lanche6, Lanche7, Jantar1, Jantar2, Jantar3, Jantar4, Jantar5, Jantar6, Jantar7, Ceia1, Ceia2, Ceia3, Ceia4, Ceia5, Ceia6, Ceia7;  
    String opcao4, opcao5, opcao6, opcao7, opcao8, opcao9, opcao10, opcao11, opcao12, opcao13, opcao14, opcao15;  
    double id1;
    
    public CadastrarPlanoAlimentar() 
    {
        initComponents();
        id = opcao1 = opcao2 = opcao3 = Desjejum1 = Desjejum2 = Desjejum3 = Desjejum4 = Desjejum5 = Desjejum6 = Desjejum7 = Almoco1 = Almoco2 = Almoco3 = Almoco4 = Almoco5 = Almoco6 = Almoco7 = Lanche1 = Lanche2 = Lanche3 = Lanche4 = Lanche5 = Lanche6 = Lanche7 = Jantar1 = Jantar2 = Jantar3 = Jantar4 = Jantar5 = Jantar6 = Jantar7 = Ceia1 = Ceia2 = Ceia3 = Ceia4 = Ceia5 = Ceia6 = Ceia7 = "";
        id1 = 0;
        opcao4 = opcao5 = opcao6 = opcao7 = opcao8 = opcao9 = opcao10 = opcao11 = opcao12 = opcao13 = opcao14 = opcao15 = "";
    }
    
    public void Exportarid_cliente(id_cliente model1)
    {
        CampoId_Cliente.setText(model1.getid_cliente());
        id = CampoId_Cliente.getText();
        id1 = Double.parseDouble(id);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        BotaoHome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPlanoAlimentar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CampoId_Cliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BotaoCadPA = new javax.swing.JButton();
        BotaoCadALmoco = new javax.swing.JButton();
        BotaoCadLT = new javax.swing.JButton();
        BotaoCadJantar = new javax.swing.JButton();
        BotaoCadCeia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 150, 0));
        jLabelTitulo.setText("Plano Alimentar");

        BotaoHome.setBackground(new java.awt.Color(215, 215, 215));
        BotaoHome.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoHome.setForeground(new java.awt.Color(0, 150, 0));
        BotaoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/Home.png"))); // NOI18N
        BotaoHome.setText("Home");
        BotaoHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoHomeActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(200, 200, 200));
        jScrollPane1.setForeground(new java.awt.Color(0, 150, 0));

        TabelaPlanoAlimentar.setBackground(new java.awt.Color(215, 215, 215));
        TabelaPlanoAlimentar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        TabelaPlanoAlimentar.setForeground(new java.awt.Color(0, 150, 0));
        TabelaPlanoAlimentar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Desjejum", null, null, null},
                {"Almoço", null, null, null},
                {"Lanche daTarde", null, null, null},
                {"Jantar", null, null, null},
                {"Ceia", null, null, null}
            },
            new String [] {
                "", "Opção 1", "Opção 2", "Opção 3"
            }
        ));
        jScrollPane1.setViewportView(TabelaPlanoAlimentar);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 150, 0));
        jLabel1.setText("Após editar a tabela, selecione um tipo de refeição e em seguida clique no botão correspondente a refeição para cadastrar ");

        CampoId_Cliente.setEditable(false);
        CampoId_Cliente.setBackground(new java.awt.Color(200, 200, 200));
        CampoId_Cliente.setForeground(new java.awt.Color(200, 200, 200));
        CampoId_Cliente.setBorder(null);
        CampoId_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoId_ClienteActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(200, 200, 200));

        BotaoCadPA.setBackground(new java.awt.Color(215, 215, 215));
        BotaoCadPA.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoCadPA.setForeground(new java.awt.Color(0, 150, 0));
        BotaoCadPA.setText("Cadastrar Desjejum");
        BotaoCadPA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoCadPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadPAActionPerformed(evt);
            }
        });

        BotaoCadALmoco.setBackground(new java.awt.Color(215, 215, 215));
        BotaoCadALmoco.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoCadALmoco.setForeground(new java.awt.Color(0, 150, 0));
        BotaoCadALmoco.setText("Cadastrar Almoco");
        BotaoCadALmoco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoCadALmoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadALmocoActionPerformed(evt);
            }
        });

        BotaoCadLT.setBackground(new java.awt.Color(215, 215, 215));
        BotaoCadLT.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoCadLT.setForeground(new java.awt.Color(0, 150, 0));
        BotaoCadLT.setText("Cadastrar Lanche da Tarde");
        BotaoCadLT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoCadLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadLTActionPerformed(evt);
            }
        });

        BotaoCadJantar.setBackground(new java.awt.Color(215, 215, 215));
        BotaoCadJantar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoCadJantar.setForeground(new java.awt.Color(0, 150, 0));
        BotaoCadJantar.setText("Cadastrar Jantar");
        BotaoCadJantar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoCadJantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadJantarActionPerformed(evt);
            }
        });

        BotaoCadCeia.setBackground(new java.awt.Color(215, 215, 215));
        BotaoCadCeia.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoCadCeia.setForeground(new java.awt.Color(0, 150, 0));
        BotaoCadCeia.setText("Cadastrar Ceia");
        BotaoCadCeia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoCadCeia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadCeiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoCadPA)
                .addGap(7, 7, 7)
                .addComponent(BotaoCadALmoco, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoCadLT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoCadJantar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoCadCeia)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCadPA)
                    .addComponent(BotaoCadALmoco)
                    .addComponent(BotaoCadLT)
                    .addComponent(BotaoCadJantar)
                    .addComponent(BotaoCadCeia))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(409, 409, 409)
                .addComponent(CampoId_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1288, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTitulo)
                        .addComponent(CampoId_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotaoHome))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.getAccessibleContext().setAccessibleName("");
        jScrollPane1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1304, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadPAActionPerformed
        opcao1 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 1).toString();
        opcao2 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 2).toString();
        opcao3 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 3).toString();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoDB", "root", "");
            Statement stm = con.createStatement();
            stm.executeUpdate("INSERT INTO desjejum(opcao1, opcao2, opcao3, id_cliente) VALUES('"+opcao1+"', '"+opcao2+"', '"+opcao3+"', '"+id1+"')");
            JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso", "Concluído", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoCadPAActionPerformed

    private void BotaoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoHomeActionPerformed
        principal_nutricionista PriN = new principal_nutricionista();
        PriN.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoHomeActionPerformed

    private void CampoId_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoId_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoId_ClienteActionPerformed

    private void BotaoCadALmocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadALmocoActionPerformed
        opcao1 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 1).toString();
        opcao2 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 2).toString();
        opcao3 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 3).toString();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoDB", "root", "");
            Statement stm = con.createStatement();
            stm.executeUpdate("INSERT INTO almoco(opcao1, opcao2, opcao3, id_cliente) VALUES('"+opcao1+"', '"+opcao2+"', '"+opcao3+"', '"+id1+"')");
            JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso", "Concluído", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoCadALmocoActionPerformed

    private void BotaoCadLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadLTActionPerformed
        opcao1 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 1).toString();
        opcao2 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 2).toString();
        opcao3 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 3).toString();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoDB", "root", "");
            Statement stm = con.createStatement();
            stm.executeUpdate("INSERT INTO lancheTarde(opcao1, opcao2, opcao3, id_cliente) VALUES('"+opcao1+"', '"+opcao2+"', '"+opcao3+"', '"+id1+"')");
            JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso", "Concluído", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoCadLTActionPerformed

    private void BotaoCadJantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadJantarActionPerformed
        opcao1 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 1).toString();
        opcao2 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 2).toString();
        opcao3 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 3).toString();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoDB", "root", "");
            Statement stm = con.createStatement();
            stm.executeUpdate("INSERT INTO jantar(opcao1, opcao2, opcao3, id_cliente) VALUES('"+opcao1+"', '"+opcao2+"', '"+opcao3+"', '"+id1+"')");
            JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso", "Concluído", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoCadJantarActionPerformed

    private void BotaoCadCeiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadCeiaActionPerformed
        opcao1 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 1).toString();
        opcao2 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 2).toString();
        opcao3 = TabelaPlanoAlimentar.getValueAt(TabelaPlanoAlimentar.getSelectedRow(), 3).toString();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoDB", "root", "");
            Statement stm = con.createStatement();
            stm.executeUpdate("INSERT INTO ceia(opcao1, opcao2, opcao3, id_cliente) VALUES('"+opcao1+"', '"+opcao2+"', '"+opcao3+"', '"+id1+"')");
            JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso", "Concluído", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoCadCeiaActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadALmoco;
    private javax.swing.JButton BotaoCadCeia;
    private javax.swing.JButton BotaoCadJantar;
    private javax.swing.JButton BotaoCadLT;
    private javax.swing.JButton BotaoCadPA;
    private javax.swing.JButton BotaoHome;
    private javax.swing.JTextField CampoId_Cliente;
    private javax.swing.JTable TabelaPlanoAlimentar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
