/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author gbdso
 */
public class CadastroCliente extends javax.swing.JFrame {
    public String id_cadastro_cliente;
    String usuario_cliente, senha_cliente, opcao1, opcao2, opcao3, ID, nome_cliente, cpf_cliente, peso_atual, peso_inicial, massa_magra, massa_gorda, sexo, idade;
    double id_cadastro_cliente1, ID1,peso_atual1, peso_inicial1, massa_magra1, massa_gorda1, cpf_cliente1, idade1;
    int sex;
    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        usuario_cliente = senha_cliente = opcao1 = opcao2 = opcao3 = id_cadastro_cliente = ID = nome_cliente = cpf_cliente = peso_atual = peso_inicial = massa_gorda = massa_magra = sexo = idade = "";
        id_cadastro_cliente1 = ID1 = peso_atual1 = peso_inicial1 = massa_magra1 = massa_gorda1 = cpf_cliente1 = idade1 = 0;
        sex = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_nome = new javax.swing.JLabel();
        jLabel_cpf = new javax.swing.JLabel();
        jLabel_peso_inicial = new javax.swing.JLabel();
        jLabel_peso_atual = new javax.swing.JLabel();
        jLabel_massa_magra = new javax.swing.JLabel();
        jLabel_massa_gorda = new javax.swing.JLabel();
        CampoNomeCliente = new javax.swing.JTextField();
        CampoCPFCliente = new javax.swing.JTextField();
        CampoPesoInicial = new javax.swing.JTextField();
        CampoPesoAtual = new javax.swing.JTextField();
        CampoMassaMagra = new javax.swing.JTextField();
        jLabel_kg_massa_magra = new javax.swing.JLabel();
        jLabel_kg_massa_gorda = new javax.swing.JLabel();
        jLabel_kg_peso_inicial = new javax.swing.JLabel();
        jLabel_kg_peso_atual = new javax.swing.JLabel();
        BotaoCadastrarCliente = new javax.swing.JButton();
        BotaoSelecionarSexo = new javax.swing.JComboBox<>();
        jLabel_sexo = new javax.swing.JLabel();
        BotaoVoltar = new javax.swing.JButton();
        jLabelIdade = new javax.swing.JLabel();
        CampoIdade = new javax.swing.JTextField();
        Campo_id_cliente = new javax.swing.JTextField();
        jLabel_usuario = new javax.swing.JLabel();
        CampoMassaGorda = new javax.swing.JTextField();
        CampoUsuario = new javax.swing.JTextField();
        CampoSenha = new javax.swing.JPasswordField();
        jLabel_senha = new javax.swing.JLabel();
        BotaoHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));

        jLabel_nome.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_nome.setForeground(new java.awt.Color(0, 150, 0));
        jLabel_nome.setText("Nome");

        jLabel_cpf.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_cpf.setForeground(new java.awt.Color(0, 150, 0));
        jLabel_cpf.setText("CPF");

        jLabel_peso_inicial.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_peso_inicial.setForeground(new java.awt.Color(0, 150, 0));
        jLabel_peso_inicial.setText("Peso Inicial");

        jLabel_peso_atual.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_peso_atual.setForeground(new java.awt.Color(0, 150, 0));
        jLabel_peso_atual.setText("Peso Atual ");

        jLabel_massa_magra.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_massa_magra.setForeground(new java.awt.Color(0, 150, 0));
        jLabel_massa_magra.setText("Massa Magra");

        jLabel_massa_gorda.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_massa_gorda.setForeground(new java.awt.Color(0, 150, 0));
        jLabel_massa_gorda.setText("Massa Gorda");

        CampoNomeCliente.setBackground(new java.awt.Color(215, 215, 215));
        CampoNomeCliente.setForeground(new java.awt.Color(0, 150, 0));
        CampoNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeClienteActionPerformed(evt);
            }
        });

        CampoCPFCliente.setBackground(new java.awt.Color(215, 215, 215));
        CampoCPFCliente.setForeground(new java.awt.Color(0, 150, 0));

        CampoPesoInicial.setBackground(new java.awt.Color(215, 215, 215));
        CampoPesoInicial.setForeground(new java.awt.Color(0, 150, 0));

        CampoPesoAtual.setBackground(new java.awt.Color(215, 215, 215));
        CampoPesoAtual.setForeground(new java.awt.Color(0, 150, 0));

        CampoMassaMagra.setBackground(new java.awt.Color(215, 215, 215));
        CampoMassaMagra.setForeground(new java.awt.Color(0, 150, 0));

        jLabel_kg_massa_magra.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_kg_massa_magra.setForeground(new java.awt.Color(0, 150, 0));
        jLabel_kg_massa_magra.setText("kg");

        jLabel_kg_massa_gorda.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_kg_massa_gorda.setForeground(new java.awt.Color(0, 150, 0));
        jLabel_kg_massa_gorda.setText("kg");

        jLabel_kg_peso_inicial.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_kg_peso_inicial.setForeground(new java.awt.Color(0, 150, 0));
        jLabel_kg_peso_inicial.setText("kg");

        jLabel_kg_peso_atual.setBackground(new java.awt.Color(200, 200, 200));
        jLabel_kg_peso_atual.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_kg_peso_atual.setForeground(new java.awt.Color(0, 150, 0));
        jLabel_kg_peso_atual.setText("kg");

        BotaoCadastrarCliente.setBackground(new java.awt.Color(215, 215, 215));
        BotaoCadastrarCliente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoCadastrarCliente.setForeground(new java.awt.Color(0, 150, 0));
        BotaoCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/EntrarConfirmar.png"))); // NOI18N
        BotaoCadastrarCliente.setText("Cadastrar Cliente");
        BotaoCadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarClienteActionPerformed(evt);
            }
        });

        BotaoSelecionarSexo.setBackground(new java.awt.Color(215, 215, 215));
        BotaoSelecionarSexo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoSelecionarSexo.setForeground(new java.awt.Color(0, 150, 0));
        BotaoSelecionarSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        BotaoSelecionarSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSelecionarSexoActionPerformed(evt);
            }
        });

        jLabel_sexo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_sexo.setForeground(new java.awt.Color(0, 150, 0));
        jLabel_sexo.setText("Sexo");

        BotaoVoltar.setBackground(new java.awt.Color(215, 215, 215));
        BotaoVoltar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoVoltar.setForeground(new java.awt.Color(0, 150, 0));
        BotaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/Voltar.png"))); // NOI18N
        BotaoVoltar.setText("Voltar");
        BotaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        jLabelIdade.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabelIdade.setForeground(new java.awt.Color(0, 150, 0));
        jLabelIdade.setText("Idade");

        CampoIdade.setBackground(new java.awt.Color(215, 215, 215));
        CampoIdade.setForeground(new java.awt.Color(0, 150, 0));

        Campo_id_cliente.setEditable(false);
        Campo_id_cliente.setBackground(new java.awt.Color(200, 200, 200));
        Campo_id_cliente.setBorder(null);
        Campo_id_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_id_clienteActionPerformed(evt);
            }
        });

        jLabel_usuario.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_usuario.setForeground(new java.awt.Color(0, 150, 0));
        jLabel_usuario.setText("Usuario:");

        CampoMassaGorda.setBackground(new java.awt.Color(215, 215, 215));
        CampoMassaGorda.setForeground(new java.awt.Color(0, 150, 0));

        CampoUsuario.setBackground(new java.awt.Color(215, 215, 215));
        CampoUsuario.setForeground(new java.awt.Color(0, 150, 0));

        CampoSenha.setBackground(new java.awt.Color(215, 215, 215));
        CampoSenha.setForeground(new java.awt.Color(0, 150, 0));
        CampoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSenhaActionPerformed(evt);
            }
        });

        jLabel_senha.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_senha.setForeground(new java.awt.Color(0, 150, 0));
        jLabel_senha.setText("Senha:");

        BotaoHome.setBackground(new java.awt.Color(215, 215, 215));
        BotaoHome.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoHome.setForeground(new java.awt.Color(0, 150, 0));
        BotaoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/Home.png"))); // NOI18N
        BotaoHome.setText("Home");
        BotaoHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoHomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 150, 0));
        jLabel1.setText("Cadastro Cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_nome)
                                    .addComponent(CampoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BotaoHome)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_usuario)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_senha)
                                            .addComponent(CampoSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(Campo_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_massa_magra)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CampoMassaMagra, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_kg_massa_magra))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel_peso_inicial)
                                            .addComponent(CampoPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_kg_peso_inicial)))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel_cpf))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(CampoPesoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel_kg_peso_atual))
                                            .addComponent(jLabel_peso_atual)
                                            .addComponent(CampoCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(CampoMassaGorda, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel_kg_massa_gorda))
                                            .addComponent(jLabel_massa_gorda))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotaoVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotaoCadastrarCliente)
                                .addGap(37, 37, 37)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel_sexo)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIdade)
                            .addComponent(BotaoSelecionarSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(BotaoHome)
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nome)
                    .addComponent(jLabel_sexo)
                    .addComponent(jLabel_cpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoSelecionarSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_peso_inicial)
                    .addComponent(jLabel_peso_atual)
                    .addComponent(jLabelIdade))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_kg_peso_inicial)
                    .addComponent(CampoPesoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_kg_peso_atual)
                    .addComponent(CampoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_massa_gorda)
                    .addComponent(jLabel_massa_magra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoMassaMagra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_kg_massa_magra)
                    .addComponent(jLabel_kg_massa_gorda)
                    .addComponent(CampoMassaGorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Campo_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_senha)
                            .addComponent(jLabel_usuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCadastrarCliente)
                    .addComponent(BotaoVoltar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(539, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeClienteActionPerformed

    private void BotaoCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarClienteActionPerformed
        if(CampoNomeCliente.getText().compareTo("") == 0 || CampoCPFCliente.getText().compareTo("") == 0 || CampoPesoInicial.getText().compareTo("") == 0 || CampoPesoAtual.getText().compareTo("") == 0 || CampoMassaMagra.getText().compareTo("") == 0 || CampoUsuario.getText().compareTo("") == 0 || CampoUsuario.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(null,"Erro \n Há dados faltando nos campos","Erro", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            usuario_cliente = CampoUsuario.getText();
            senha_cliente = CampoSenha.getText();
            nome_cliente = CampoNomeCliente.getText();
            cpf_cliente = CampoCPFCliente.getText();
            cpf_cliente1 = Double.parseDouble(cpf_cliente);
            idade = CampoIdade.getText();
            idade1 = Double.parseDouble(idade);
            peso_atual = CampoPesoAtual.getText();
            peso_atual1 = Double.parseDouble(peso_atual);
            peso_inicial = CampoPesoInicial.getText();
            peso_inicial1 = Double.parseDouble(peso_atual);
            massa_magra = CampoMassaMagra.getText();
            massa_magra1 = Double.parseDouble(massa_magra);
            massa_gorda = CampoMassaGorda.getText();
            massa_gorda1 = Double.parseDouble(massa_gorda);
            sex = BotaoSelecionarSexo.getSelectedIndex();
            if(sex == 0)
            {
                sexo = "Masculino";
            }
            else if(sex == 1)
            {
                sexo = "Feminino";
            }
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoDB", "root", "");
                Statement stm = con.createStatement();
                stm.executeUpdate("INSERT INTO cliente(user_cliente, senha_cliente, nivel_acesso, nome_cliente, cpf_cliente, idade_cliente , peso_cliente, peso_atual, massa_magra, massa_gorda, sexo_cliente) VALUES('"+usuario_cliente+"', '"+senha_cliente+"','cliente', '"+nome_cliente+"', '"+cpf_cliente1+"', '"+idade1+"', '"+peso_inicial1+"', '"+peso_atual1+"', '"+massa_magra1+"', '"+massa_gorda1+"', '"+sexo+"')");
                JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso", "Concluído", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(ClassNotFoundException ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }       
    }//GEN-LAST:event_BotaoCadastrarClienteActionPerformed

    private void BotaoSelecionarSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSelecionarSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoSelecionarSexoActionPerformed

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        principal_nutricionista priN = new principal_nutricionista();
        priN.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void Campo_id_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_id_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_id_clienteActionPerformed

    private void CampoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSenhaActionPerformed

    private void BotaoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoHomeActionPerformed
        principal_nutricionista PriN = new principal_nutricionista();
        PriN.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoHomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrarCliente;
    private javax.swing.JButton BotaoHome;
    private javax.swing.JComboBox<String> BotaoSelecionarSexo;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JTextField CampoCPFCliente;
    private javax.swing.JTextField CampoIdade;
    private javax.swing.JTextField CampoMassaGorda;
    private javax.swing.JTextField CampoMassaMagra;
    private javax.swing.JTextField CampoNomeCliente;
    private javax.swing.JTextField CampoPesoAtual;
    private javax.swing.JTextField CampoPesoInicial;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JTextField Campo_id_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabel_cpf;
    private javax.swing.JLabel jLabel_kg_massa_gorda;
    private javax.swing.JLabel jLabel_kg_massa_magra;
    private javax.swing.JLabel jLabel_kg_peso_atual;
    private javax.swing.JLabel jLabel_kg_peso_inicial;
    private javax.swing.JLabel jLabel_massa_gorda;
    private javax.swing.JLabel jLabel_massa_magra;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_peso_atual;
    private javax.swing.JLabel jLabel_peso_inicial;
    private javax.swing.JLabel jLabel_senha;
    private javax.swing.JLabel jLabel_sexo;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
