/*
* Tela de login com nível de acesso de nutricionista e secretaria
*/
package interfaces;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author gbdso
 */
public class login extends javax.swing.JFrame{
    String name, id, nivel_acesso, usuario_cliente, senha_cliente , usuario, senha, usuarioBD, senhaBD, level_access, cliente_BD, senha_cliente_BD;
    double id1;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        name = id = nivel_acesso = usuario_cliente = senha_cliente = usuario = senha = usuarioBD = senhaBD = level_access = cliente_BD = senha_cliente_BD = "";
        id1 = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotaoEntrar = new javax.swing.JButton();
        CampoSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CampoLogin = new javax.swing.JTextField();
        BotaoSelecionarNivelAcesso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));

        BotaoEntrar.setBackground(new java.awt.Color(215, 215, 215));
        BotaoEntrar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoEntrar.setForeground(new java.awt.Color(0, 150, 0));
        BotaoEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/EntrarConfirmar.png"))); // NOI18N
        BotaoEntrar.setText("Entrar");
        BotaoEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEntrarActionPerformed(evt);
            }
        });
        BotaoEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotaoEntrarKeyPressed(evt);
            }
        });

        CampoSenha.setBackground(new java.awt.Color(215, 215, 215));
        CampoSenha.setForeground(new java.awt.Color(0, 150, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 150, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Usuário");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 150, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Senha");

        CampoLogin.setBackground(new java.awt.Color(215, 215, 215));
        CampoLogin.setForeground(new java.awt.Color(0, 150, 0));
        CampoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoLoginActionPerformed(evt);
            }
        });

        BotaoSelecionarNivelAcesso.setBackground(new java.awt.Color(200, 200, 200));
        BotaoSelecionarNivelAcesso.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoSelecionarNivelAcesso.setForeground(new java.awt.Color(0, 150, 0));
        BotaoSelecionarNivelAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nutricionista", "Cliente" }));
        BotaoSelecionarNivelAcesso.setToolTipText("");
        BotaoSelecionarNivelAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSelecionarNivelAcessoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotaoEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(BotaoSelecionarNivelAcesso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(201, 201, 201))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoSelecionarNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BotaoEntrar)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(543, 334));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEntrarActionPerformed
        int status = 0;
        int lvl = 0;
        usuario = CampoLogin.getText();
        senha = CampoSenha.getText();
        usuario_cliente = CampoLogin.getText();
        senha_cliente = CampoSenha.getText();
        lvl = BotaoSelecionarNivelAcesso.getSelectedIndex();
        if(lvl == 0)
        {
            nivel_acesso = "nutricionista";
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoDB", "root", "");
                Statement stm = con.createStatement();
                ResultSet res = stm.executeQuery("SELECT * FROM usuarios");
                while(res.next())
                {
                    usuarioBD = res.getString("login_usuario");
                    senhaBD = res.getString("senha_usuario");
                    level_access = res.getString("nivel_acesso");
                    if(usuario.equals(usuarioBD) && senha.equals(senhaBD) && level_access.equals("nutricionista"))
                    {
                        status = 1;
                    }
                }
                if(status == 1)
                {
                    principal_nutricionista priN = new principal_nutricionista();
                    priN.setVisible(true);
                    this.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Usúario ou senha incorretos","Tente novamente", JOptionPane.INFORMATION_MESSAGE);
                    CampoLogin.setText("");
                    CampoSenha.setText("");
                }
            }
            catch(ClassNotFoundException ex)
            {
                JOptionPane.showMessageDialog(null, "Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, "Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(lvl == 1)
        {         
            nivel_acesso = "cliente";
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoDB", "root", "");
                Statement stm = con.createStatement();
                ResultSet res = stm.executeQuery("SELECT * FROM cliente");
                while(res.next())
                {
                    cliente_BD = res.getString("user_cliente");
                    senha_cliente_BD = res.getString("senha_cliente");
                    nivel_acesso = res.getString("nivel_acesso");
                    if(usuario_cliente.equals(cliente_BD) && senha_cliente.equals(senha_cliente_BD) && nivel_acesso.equals("cliente"))
                    {
                        status = 2;
                        id = res.getString("cliente_id");
                        id1 = Double.parseDouble(id);
                        name = res.getString("nome_cliente");
                    }
                }
                if(status == 2)
                {
                    principal_paciente prinP = new principal_paciente(id1);
                    prinP.setVisible(true);
                    this.dispose();
                    
                    id_cliente id_do_paciente = new id_cliente();
                    id_do_paciente.setcliente(id);
                    prinP.Exportarid_perfilcliente(id_do_paciente);
                    
                    cliente model = new cliente();
                    model.setcliente(name);
                    prinP.ExportarNome(model);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Usúario ou senha incorretos","Tente novamente", JOptionPane.INFORMATION_MESSAGE);
                    CampoLogin.setText("");
                    CampoSenha.setText("");
                }
            }
            catch(ClassNotFoundException ex)
            {
                JOptionPane.showMessageDialog(null, "Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, "Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BotaoEntrarActionPerformed

    private void CampoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoLoginActionPerformed

    private void BotaoEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotaoEntrarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoEntrarKeyPressed

    private void BotaoSelecionarNivelAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSelecionarNivelAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoSelecionarNivelAcessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoEntrar;
    private javax.swing.JComboBox<String> BotaoSelecionarNivelAcesso;
    private javax.swing.JTextField CampoLogin;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
