/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel Baptista
 * @author Rodrigo Augusto
 * @author Joao Pedro dos Santos
 */
public class MostrarPacientes extends javax.swing.JFrame 
{
    String nome, ID, cpf, peso_at, massa_m, massa_g, sexo;
    double ID1, CPF1, peso_at1, massa_m1, massa_g1;
    public MostrarPacientes() {
        initComponents();
        nome = ID = cpf = peso_at = massa_m = massa_g = sexo = "";
        ID1 = CPF1 = peso_at1 = massa_m1 = massa_g1 = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCLientes = new javax.swing.JTable();
        BarraPesquisa = new javax.swing.JTextField();
        fechar = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        BotaoPesquisar = new javax.swing.JButton();
        BotaoHome = new javax.swing.JToggleButton();
        PesquisaIDCLiente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(200, 200, 200));
        setLocation(new java.awt.Point(300, 135));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelaCLientes.setBackground(new java.awt.Color(215, 215, 215));
        TabelaCLientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 126, 140), 2));
        TabelaCLientes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TabelaCLientes.setForeground(new java.awt.Color(0, 150, 0));
        TabelaCLientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaCLientes.setSelectionBackground(new java.awt.Color(153, 153, 153));
        TabelaCLientes.getTableHeader().setReorderingAllowed(false);
        TabelaCLientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaCLientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaCLientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 740, 350));

        BarraPesquisa.setEditable(false);
        BarraPesquisa.setBackground(new java.awt.Color(215, 215, 215));
        BarraPesquisa.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BarraPesquisa.setForeground(new java.awt.Color(0, 150, 0));
        BarraPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(BarraPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 570, 30));

        fechar.setBackground(new java.awt.Color(215, 215, 215));
        fechar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        fechar.setForeground(new java.awt.Color(0, 150, 0));
        fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/Sair.png"))); // NOI18N
        fechar.setText("Fechar");
        fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });
        getContentPane().add(fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 140, 30));

        minimizar.setBackground(new java.awt.Color(215, 215, 215));
        minimizar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        minimizar.setForeground(new java.awt.Color(0, 150, 0));
        minimizar.setText("Minimizar");
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 130, 30));

        BotaoPesquisar.setBackground(new java.awt.Color(215, 215, 215));
        BotaoPesquisar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoPesquisar.setForeground(new java.awt.Color(0, 150, 0));
        BotaoPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/MostrarPerfilV.png"))); // NOI18N
        BotaoPesquisar.setText("Mostrar Perfil");
        BotaoPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 140, 30));

        BotaoHome.setBackground(new java.awt.Color(215, 215, 215));
        BotaoHome.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoHome.setForeground(new java.awt.Color(0, 150, 0));
        BotaoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/Home.png"))); // NOI18N
        BotaoHome.setText("Home");
        BotaoHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoHomeActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        PesquisaIDCLiente.setBackground(new java.awt.Color(200, 200, 200));
        PesquisaIDCLiente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        PesquisaIDCLiente.setForeground(new java.awt.Color(200, 200, 200));
        PesquisaIDCLiente.setUI(null);
        getContentPane().add(PesquisaIDCLiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 570, -1));

        setSize(new java.awt.Dimension(799, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void TabelaCLientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCLientesMouseClicked
        BarraPesquisa.setText(TabelaCLientes.getValueAt(TabelaCLientes.getSelectedRow(), 1).toString());
        PesquisaIDCLiente.setText(TabelaCLientes.getValueAt(TabelaCLientes.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_TabelaCLientesMouseClicked

    private void BarraPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraPesquisaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        this.consultaDados("SELECT * FROM cliente ORDER BY nome_cliente");

    }

    public void consultaDados(String sql) 
    {
        try 
        {
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoDB", "root", "");
            PreparedStatement banco = (PreparedStatement) con.prepareStatement(sql);
            banco.execute();
            ResultSet dados = banco.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) TabelaCLientes.getModel();
            model.setNumRows(0);

            while (dados.next()) 
            {
                model.addRow(new Object[]
                {
                    dados.getString("cliente_id"),
                    dados.getString("nome_cliente"),
                    dados.getString("cpf_cliente"),
                });
                ID = dados.getString("cliente_id");
                ID1 = Double.parseDouble(ID);
                nome = dados.getString("nome_cliente");
                cpf = dados.getString("cpf_cliente");
                CPF1 = Double.parseDouble(cpf);   
            }
            banco.close();
            con.close();
        } 
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened
   
    private void BotaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesquisarActionPerformed
        if(BarraPesquisa.getText().compareTo("")==0)
        {
            JOptionPane.showMessageDialog(null,"Erro \n Nenhum usuário foi selecionado","Erro", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            PerfilPacienteNutri PacienteNut = new PerfilPacienteNutri(ID1, CPF1);
            PacienteNut.setVisible(true);
            this.dispose();
        
            cliente model = new cliente();
            model.setcliente(BarraPesquisa.getText());
            PacienteNut.ExportarNome(model);
            
            id_cliente model1 = new id_cliente();
            model1.setcliente(PesquisaIDCLiente.getText());
            PacienteNut.Exportarid_cliente(model1);            
        }
    }//GEN-LAST:event_BotaoPesquisarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_fecharActionPerformed

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizarActionPerformed

    private void BotaoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoHomeActionPerformed
        principal_nutricionista PriN = new principal_nutricionista();
        PriN.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoHomeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraPesquisa;
    private javax.swing.JToggleButton BotaoHome;
    private javax.swing.JButton BotaoPesquisar;
    private javax.swing.JTextField PesquisaIDCLiente;
    private javax.swing.JTable TabelaCLientes;
    private javax.swing.JButton fechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton minimizar;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cliente
     */
}
