/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class principal_paciente extends javax.swing.JFrame {
    ConexaoBD conecta =  new ConexaoBD();
    String id;
    double id1, novo_id;
    /**
     * Creates new form principal_paciente
     */
    public principal_paciente(double id1) {
        initComponents();
        conecta.conexao();
        id = "";
        id1 = novo_id = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BotaoShowConsultas = new javax.swing.JButton();
        BotaoPerfil = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nome = new javax.swing.JTextField();
        CampoId_Cliente = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 150, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 3, true));

        BotaoShowConsultas.setBackground(new java.awt.Color(0, 100, 0));
        BotaoShowConsultas.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoShowConsultas.setForeground(new java.awt.Color(200, 200, 200));
        BotaoShowConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/MostrarConsultas.png"))); // NOI18N
        BotaoShowConsultas.setText("Mostrar Consultas");
        BotaoShowConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoShowConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoShowConsultasActionPerformed(evt);
            }
        });

        BotaoPerfil.setBackground(new java.awt.Color(0, 100, 0));
        BotaoPerfil.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoPerfil.setForeground(new java.awt.Color(200, 200, 200));
        BotaoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/MostrarPerfil.png"))); // NOI18N
        BotaoPerfil.setText("Mostar Perfil");
        BotaoPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPerfilActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(200, 200, 200));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 150, 0));
        jLabel1.setText("Bem Vindo ao YinYang!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel1)
                .addGap(246, 246, 246))
        );

        jButton1.setBackground(new java.awt.Color(0, 100, 0));
        jButton1.setForeground(new java.awt.Color(200, 200, 200));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/SairB.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nome.setEditable(false);
        nome.setBackground(new java.awt.Color(200, 200, 200));
        nome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nome.setForeground(new java.awt.Color(0, 150, 0));
        nome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nome.setUI(null);
        nome.setBorder(null);
        nome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotaoShowConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(BotaoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(BotaoShowConsultas)
                .addGap(120, 120, 120)
                .addComponent(BotaoPerfil)
                .addGap(120, 120, 120)
                .addComponent(jButton1)
                .addGap(119, 119, 119))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CampoId_Cliente.setEditable(false);
        CampoId_Cliente.setUI(null);
        CampoId_Cliente.setDoubleBuffered(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(420, 420, 420)
                    .addComponent(CampoId_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(253, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addComponent(CampoId_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(274, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(993, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void Exportarid_perfilcliente(id_cliente model1)
    {
        CampoId_Cliente.setText(model1.getid_cliente());
        id = CampoId_Cliente.getText();
        id1 = Double.parseDouble(id);
    }
    
    public void ExportarNome(cliente model)
    {
        nome.setText(model.getcliente());
    }
    
    private void BotaoShowConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoShowConsultasActionPerformed
        MostrarConsultasPaciente ConsultP = new MostrarConsultasPaciente();
        ConsultP.setVisible(true);
    }//GEN-LAST:event_BotaoShowConsultasActionPerformed

    private void BotaoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPerfilActionPerformed
       PerfilPacientePaciente perfil_do_paciente = new PerfilPacientePaciente(id1);
       perfil_do_paciente.setVisible(true);
       this.dispose();
       
       id_cliente id_do_paciente = new id_cliente();
       id_do_paciente.setcliente(id);
       perfil_do_paciente.Exportarid_perfilcliente(id_do_paciente);
       
       cliente model = new cliente();
       model.setcliente(nome.getText());
       perfil_do_paciente.ExportarNome(model);
              
    }//GEN-LAST:event_BotaoPerfilActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetoDB", "root", "");
                Statement stm = con.createStatement();
                ResultSet res = stm.executeQuery("SELECT * FROM cliente WHERE cliente_id = '"+id1+"'");
                while(res.next())
                {
                    novo_id = id1;
                }
            }
            catch(ClassNotFoundException ex)
            {
                JOptionPane.showMessageDialog(null, "Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, "Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        conecta.desconecta();
        login log = new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoPerfil;
    private javax.swing.JButton BotaoShowConsultas;
    private javax.swing.JTextField CampoId_Cliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nome;
    // End of variables declaration//GEN-END:variables
}
