/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
import javax.swing.JOptionPane;
/**
 *
 * @author gbdso
 */
public class principal_nutricionista extends javax.swing.JFrame {
    ConexaoBD conecta =  new ConexaoBD();
    /**
     * Creates new form principal_nutricionista
     */
    public principal_nutricionista() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        BotaoAgendarConsultas = new javax.swing.JButton();
        BotaoCadastroCliente = new javax.swing.JButton();
        BotaoCadUser = new javax.swing.JButton();
        BotaoShowConsultas = new javax.swing.JButton();
        BotaoMostrarPacientes = new javax.swing.JButton();
        BotaoSair = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 150, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 0), new java.awt.Color(51, 153, 0), new java.awt.Color(51, 153, 0), new java.awt.Color(51, 153, 0)));
        jPanel2.setForeground(new java.awt.Color(51, 255, 0));

        BotaoAgendarConsultas.setBackground(new java.awt.Color(0, 100, 0));
        BotaoAgendarConsultas.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoAgendarConsultas.setForeground(new java.awt.Color(200, 200, 200));
        BotaoAgendarConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/AgendarConsulta.png"))); // NOI18N
        BotaoAgendarConsultas.setText("Agendar Consulta");
        BotaoAgendarConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoAgendarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAgendarConsultasActionPerformed(evt);
            }
        });

        BotaoCadastroCliente.setBackground(new java.awt.Color(0, 100, 0));
        BotaoCadastroCliente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoCadastroCliente.setForeground(new java.awt.Color(200, 200, 200));
        BotaoCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/CadastrarPaciente.png"))); // NOI18N
        BotaoCadastroCliente.setText("Cadastrar Paciente");
        BotaoCadastroCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroClienteActionPerformed(evt);
            }
        });

        BotaoCadUser.setBackground(new java.awt.Color(0, 100, 0));
        BotaoCadUser.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoCadUser.setForeground(new java.awt.Color(200, 200, 200));
        BotaoCadUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/CadastrarUsuario.png"))); // NOI18N
        BotaoCadUser.setText("Cadastrar Usuário");
        BotaoCadUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoCadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadUserActionPerformed(evt);
            }
        });

        BotaoShowConsultas.setBackground(new java.awt.Color(0, 100, 0));
        BotaoShowConsultas.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoShowConsultas.setForeground(new java.awt.Color(200, 200, 200));
        BotaoShowConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/MostrarConsultas.png"))); // NOI18N
        BotaoShowConsultas.setText("Mostrar Consultas");
        BotaoShowConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoShowConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoShowConsultasActionPerformed(evt);
            }
        });

        BotaoMostrarPacientes.setBackground(new java.awt.Color(0, 100, 0));
        BotaoMostrarPacientes.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BotaoMostrarPacientes.setForeground(new java.awt.Color(200, 200, 200));
        BotaoMostrarPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/MostrarPacientes.png"))); // NOI18N
        BotaoMostrarPacientes.setText("Mostrar Pacientes");
        BotaoMostrarPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotaoMostrarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoMostrarPacientesActionPerformed(evt);
            }
        });

        BotaoSair.setBackground(new java.awt.Color(0, 100, 0));
        BotaoSair.setForeground(new java.awt.Color(200, 200, 200));
        BotaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/folder/SairB.png"))); // NOI18N
        BotaoSair.setText("Sair");
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotaoShowConsultas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoCadUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoCadastroCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(BotaoMostrarPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoAgendarConsultas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(BotaoMostrarPacientes)
                .addGap(43, 43, 43)
                .addComponent(BotaoAgendarConsultas)
                .addGap(43, 43, 43)
                .addComponent(BotaoCadastroCliente)
                .addGap(43, 43, 43)
                .addComponent(BotaoCadUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(BotaoShowConsultas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(BotaoSair)
                .addGap(33, 33, 33))
        );

        jPanel4.setBackground(new java.awt.Color(200, 200, 200));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 0), new java.awt.Color(51, 153, 0), new java.awt.Color(51, 153, 0), new java.awt.Color(51, 153, 0)));
        jPanel4.setForeground(new java.awt.Color(51, 255, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 150, 0));
        jLabel1.setText("Bem Vindo ao YinYang!");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1134, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void BotaoCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroClienteActionPerformed
        CadastroCliente cadCliente = new CadastroCliente();
        cadCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoCadastroClienteActionPerformed

    private void BotaoCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadUserActionPerformed
        CadastrarUsuario cadUser = new CadastrarUsuario();
        cadUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoCadUserActionPerformed

    private void BotaoMostrarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoMostrarPacientesActionPerformed
        MostrarPacientes ShowPaciente = new MostrarPacientes();
        ShowPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoMostrarPacientesActionPerformed

    private void BotaoShowConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoShowConsultasActionPerformed
        MostrarConsultas ShowConsultas = new MostrarConsultas();
        ShowConsultas.setVisible(true);
    }//GEN-LAST:event_BotaoShowConsultasActionPerformed

    private void BotaoAgendarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAgendarConsultasActionPerformed
        FormAgenda FormAgendarPaciente = new FormAgenda();
        FormAgendarPaciente.setVisible(true);
        
    }//GEN-LAST:event_BotaoAgendarConsultasActionPerformed

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        conecta.desconecta();
        login log = new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoSairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAgendarConsultas;
    private javax.swing.JButton BotaoCadUser;
    private javax.swing.JButton BotaoCadastroCliente;
    private javax.swing.JButton BotaoMostrarPacientes;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JButton BotaoShowConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
